//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSCM.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPSCM.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于我们.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “云停车”智慧城市停车管理系统是由北京智慧星停车软件科技有限公司面向国际国内市场研发打造的世界一流的智慧停车系统平台。“云停车”系统采用了目前最先进的软硬件技术，运用“云平台”“大数据分析”的科学手段，致力于解决国际国内的大中城市存在的“停车难”的现状，为广大驾驶人解决了所有停车难题。开启了优雅驾车停车的新时代生活方式。.
        /// </summary>
        public static string AboutUsContent {
            get {
                return ResourceManager.GetString("AboutUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于我们.
        /// </summary>
        public static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap butten_cancel {
            get {
                object obj = ResourceManager.GetObject("butten_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap butten_cancel_click {
            get {
                object obj = ResourceManager.GetObject("butten_cancel_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap butten_determine {
            get {
                object obj = ResourceManager.GetObject("butten_determine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap butten_determine_click {
            get {
                object obj = ResourceManager.GetObject("butten_determine_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进出场车辆统计.
        /// </summary>
        public static string ChangeToParkingPage {
            get {
                return ResourceManager.GetString("ChangeToParkingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停车券使用统计.
        /// </summary>
        public static string ChangeToTicketPage {
            get {
                return ResourceManager.GetString("ChangeToTicketPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap interface_close {
            get {
                object obj = ResourceManager.GetObject("interface_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap interface_smallest {
            get {
                object obj = ResourceManager.GetObject("interface_smallest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳转.
        /// </summary>
        public static string JumpTo {
            get {
                return ResourceManager.GetString("JumpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳转到第.
        /// </summary>
        public static string JumpToThatPage {
            get {
                return ResourceManager.GetString("JumpToThatPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap list_butten {
            get {
                object obj = ResourceManager.GetObject("list_butten", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap list_butten_click {
            get {
                object obj = ResourceManager.GetObject("list_butten_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login_close {
            get {
                object obj = ResourceManager.GetObject("login_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap login_logo {
            get {
                object obj = ResourceManager.GetObject("login_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录帐号:.
        /// </summary>
        public static string LoginAccount {
            get {
                return ResourceManager.GetString("LoginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon logo_icon {
            get {
                object obj = ResourceManager.GetObject("logo_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /{0}页.
        /// </summary>
        public static string MaxPageFormater {
            get {
                return ResourceManager.GetString("MaxPageFormater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无更新.
        /// </summary>
        public static string NoUpdates {
            get {
                return ResourceManager.GetString("NoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_input {
            get {
                object obj = ResourceManager.GetObject("page_input", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_last {
            get {
                object obj = ResourceManager.GetObject("page_last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_next {
            get {
                object obj = ResourceManager.GetObject("page_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存帐号.
        /// </summary>
        public static string PerserveAccount {
            get {
                return ResourceManager.GetString("PerserveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh_icon {
            get {
                object obj = ResourceManager.GetObject("refresh_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_01 {
            get {
                object obj = ResourceManager.GetObject("search_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_02 {
            get {
                object obj = ResourceManager.GetObject("search_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据统计.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日共进出{0}辆车，收取停车费{1:N2}元.
        /// </summary>
        public static string TodayParkingSummaryFormater {
            get {
                return ResourceManager.GetString("TodayParkingSummaryFormater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日共使用停车券{0}张.
        /// </summary>
        public static string TodayTicketUseSummaryFormater {
            get {
                return ResourceManager.GetString("TodayTicketUseSummaryFormater", resourceCulture);
            }
        }
    }
}
